# Generated by Django 3.1.4 on 2020-12-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
    ]
