# Generated by Django 3.1.4 on 2021-01-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLevelWaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('gdp', models.IntegerField(default=0)),
                ('total_waste', models.IntegerField(default=0)),
                ('organic_pct', models.FloatField(default=0.0)),
                ('population', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='WasteSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(default=0)),
                ('trash_bag_per_week', models.IntegerField(default=0)),
                ('organic_pct', models.FloatField(default=0.0)),
            ],
        ),
    ]
