# Generated by Django 3.1.4 on 2021-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('zip_code', models.IntegerField(null=True)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(blank=True, default='', max_length=128)),
                ('total_waste_per_week', models.IntegerField(default=0)),
                ('total_food_waste_per_week', models.IntegerField(default=0)),
                ('pledged_reduction', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WasteSurvey',
        ),
    ]
