# Generated by Django 3.1.4 on 2021-01-26 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0002_auto_20210118_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgeinfo',
            name='pledged_reduction',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pledgeinfo',
            name='total_food_waste_per_week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pledgeinfo',
            name='total_waste_per_week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pledgeinfo',
            name='zip_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
